name: Deploy Vite React app to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run the TS build just like your package.json script does
      - name: TypeScript build
        run: npx tsc -b

      # Compute BASE automatically:
      # - "/" for user/org sites (e.g. myname.github.io)
      # - "/<repo>/" for project sites
      - name: Compute BASE path
        run: |
          REPO="${{ github.repository }}"            # owner/repo
          NAME="${REPO#*/}"                         # repo
          if [[ "$NAME" == *".github.io" ]]; then
            echo "BASE=/" >> $GITHUB_ENV
          else
            echo "BASE=/$NAME/" >> $GITHUB_ENV
          fi
          echo "Using BASE='$BASE'"

      # Build Vite without editing vite.config.ts
      - name: Vite build
        run: npx vite build --base "$BASE"

      # SPA fallback so client routing works on refresh
      - name: Create SPA fallback (404.html)
        run: cp dist/index.html dist/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
